version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=yourpassword
      - DB_NAME=hysteria
    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - "8081:8080"

  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: hysteria
    ports:
      - "5432:5432"
